import { useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { getPetAvatar, getPetAvatarLabel } from '../assets/petAvatar'
import { endDemoSession, getDashboardSession, getMemberProfile, getPetProfiles, updateMemberProfile } from '../demo/dashboardState'
import '../styles/account.css'

export default function Account() {
  const nav = useNavigate(); const input = useRef(null); const [profile, setProfile] = useState(getMemberProfile); const [name, setName] = useState(profile.displayName); const [notice, setNotice] = useState(''); const [logoutOpen, setLogoutOpen] = useState(false); const pets = getPetProfiles().pets
  const save = () => { const next = updateMemberProfile({ displayName: name }); setProfile(next); setName(next.displayName); setNotice('프로필을 이 브라우저의 데모 화면에 저장했어요.') }
  const photo = e => { const f=e.target.files?.[0]; if(!f)return; if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>1024*1024){setNotice('PNG, JPG, WEBP 형식의 1MB 이하 사진만 선택할 수 있어요.');return} const r=new FileReader(); r.onload=()=>{const n=updateMemberProfile({avatarDataUrl:r.result});setProfile(n);setNotice('프로필 사진을 이 브라우저에 저장했어요.')};r.readAsDataURL(f) }
  if (getDashboardSession().mode !== 'member-demo') return <main className="account-page"><section className="account-shell account-empty"><h1>프로필 관리는 로그인 후 이용할 수 있어요.</h1><Link to="/">홈으로 돌아가기</Link></section></main>
  return <main className="account-page"><section className="account-shell"><Link className="account-back" to="/my">← 마이페이지</Link><p className="account-eyebrow">MY ANIMAL-ROUTE</p><h1>프로필 관리</h1><p className="account-intro">이 정보와 사진은 이 브라우저의 데모 화면에만 저장되며 서버로 전송되지 않습니다.</p><section className="account-card account-profile-card"><div className="account-avatar">{profile.avatarDataUrl?<img src={profile.avatarDataUrl} alt="보호자 프로필 사진"/>:profile.displayName.slice(0,1)}</div><div className="account-photo"><button type="button" onClick={()=>input.current?.click()}>사진 변경</button><small>PNG, JPG, WEBP · 1MB 이하</small><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" onChange={photo}/></div><label className="account-name">보호자 이름<input value={name} maxLength="20" onChange={e=>setName(e.target.value)} /></label><button className="account-save" type="button" onClick={save}>변경사항 저장</button><p className="account-notice" role="status" aria-live="polite">{notice}</p></section><section className="account-card"><header><div><p className="account-eyebrow">MY PETS</p><h2>등록한 반려동물 {pets.length}마리</h2></div><span>추가·수정 준비 중</span></header><div className="account-pets">{pets.map(p=><article key={p.id}><i className="account-pet-avatar"><img src={getPetAvatar(p.species)} alt={getPetAvatarLabel(p.species)} /></i><div><strong>{p.name}</strong><p>{p.breed} · {p.age} · {p.sex}</p></div></article>)}</div></section><section className="account-card account-muted"><p className="account-eyebrow">RECORDS & NOTIFICATIONS</p><h2>알림과 기록 <span>준비 중</span></h2><p>알림 설정과 건강 경로 기록 저장은 실제 계정 연결 후 제공할 예정입니다.</p></section><section className="account-card account-danger"><p className="account-eyebrow">DEMO SESSION</p><h2>데모 로그아웃</h2><p>로그아웃해도 프로필 사진·반려동물·작성 중 초안은 이 브라우저에 남아 있을 수 있어요.</p><button type="button" onClick={()=>setLogoutOpen(true)}>데모 로그아웃</button></section></section>{logoutOpen&&<div className="account-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setLogoutOpen(false)}><section className="account-modal" role="dialog" aria-modal="true" aria-labelledby="logout-title"><h2 id="logout-title">데모 로그아웃할까요?</h2><p>이 브라우저의 데모 로그인 상태만 종료합니다. 프로필과 작성 중인 초안은 남아 있을 수 있어요.</p><div><button autoFocus type="button" onClick={()=>setLogoutOpen(false)}>취소</button><button className="is-danger" type="button" onClick={()=>{endDemoSession();nav('/')}}>로그아웃</button></div></section></div>}</main>
}
