import { useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { getPetAvatar, getPetAvatarLabel } from '../assets/petAvatar'
import { getPetProfiles, setActivePetId } from '../demo/dashboardState'
import { getDemoHealthRecords, getDemoVisitByRouteId } from '../demo/plusDemoState'
import VisitRecordDialog from '../components/medical/VisitRecordDialog'
import '../styles/health-records.css'

function RecordDetail({ record, pet, onClose, onVisit, visitTrigger }) { const visit=getDemoVisitByRouteId(record.id); return <div className="record-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="record-dialog" role="dialog" aria-modal="true" aria-labelledby="record-detail-title"><button className="record-close" onClick={onClose} aria-label="기록 상세 닫기">×</button><p className="record-eyebrow">건강 경로 기록 · 본선 데모 예시</p><div className="record-title"><img src={getPetAvatar(pet.species)} alt={getPetAvatarLabel(pet.species)}/><div><span>{record.date}</span><h2 id="record-detail-title">{pet.name} · {record.summary}</h2></div></div>{record.status==='urgent'&&<div className="record-urgent">응급 신호를 우선 안내했던 기록이에요. 실제 상태가 이어지거나 악화되면 가까운 동물병원에 연락하세요.</div>}<section className="record-detail-block"><h3>보호자가 입력한 내용</h3><p className="record-quote">“{record.input}”</p></section><section className="record-detail-block"><h3>확인한 표준 증상</h3><div className="record-tags">{record.symptoms.map(s=><span key={s}>{s}</span>)}</div></section><section className="record-detail-block"><h3>병원 문의 전 확인 사항</h3><p>{record.guidance}</p><b>{record.hospital}</b></section>{visit&&<section className="record-detail-block"><h3>개인 진료 기록 · Plus 데모</h3><p>병원 방문 후 보호자가 남긴 메모와 진료비 영수증 예시를 확인할 수 있어요.</p><button ref={visitTrigger} className="record-visit-button" onClick={()=>onVisit(visit)}>방문 기록 예시 보기 →</button></section>}<div className="record-actions"><Link to="/health-check">새 건강 경로 시작하기</Link><button onClick={onClose}>닫기</button></div><small>건강 경로는 보호자 관찰 내용을 정리하고 병원 문의를 돕기 위한 정보입니다. 질병 진단이나 처방을 제공하지 않습니다.</small></section></div> }
export default function HealthRecords(){const {pets,activePetId}=getPetProfiles();const [params,setParams]=useSearchParams();const [petId,setPet]=useState(params.get('pet')||activePetId||pets[0]?.id);const [selected,setSelected]=useState(null);const [visit,setVisit]=useState(null);const visitRef=useRef(null);const pet=pets.find(p=>p.id===petId)||pets[0];const records=pet?getDemoHealthRecords(pet.id):[];const choose=id=>{setPet(id);setActivePetId(id);setParams({pet:id})};if(!pet)return <main className="records-page"><div className="records-shell"><h1>등록된 반려동물이 없어요</h1></div></main>;return <main className="records-page"><div className="records-shell"><Link className="records-back" to="/my">← 내 대시보드</Link><header className="records-hero"><div><p className="record-eyebrow">MY ANIMAL-ROUTE · DEMO</p><h1>우리 아이의 건강 기록</h1><span>증상 확인과 병원 문의 준비 내용을 날짜별로 모아볼 수 있어요.</span></div><aside><b>최근 기록 3건</b><button>전체 기록 관리 <em>Plus</em></button></aside></header><p className="records-notice">이 화면은 본선 데모 예시이며 실제 서버에 건강 기록·영수증을 저장하지 않습니다.</p><div className="records-pets">{pets.map(p=><button key={p.id} className={p.id===pet.id?'is-active':''} onClick={()=>choose(p.id)}><img src={getPetAvatar(p.species)} alt=""/><span>{p.name}</span></button>)}</div><section className="records-list"><header><div><h2>{pet.name}의 최근 건강 경로</h2><span>보호자가 확인한 내용</span></div><button>기간별 보기 <em>Plus</em></button></header><div className="record-timeline">{records.map(r=><button className={'record-row '+(r.status==='urgent'?'is-urgent':'')} key={r.id} onClick={()=>setSelected(r)}><time>{r.date}</time><div><span className="record-status">{r.status==='urgent'?'! 응급 우선 안내':'✓ 표준 증상 확인 완료'}</span><strong>{r.summary}</strong><small>기록 보기 →</small></div></button>)}</div></section><section className="records-safety"><b>⌁</b><p>응급 신호는 구독 여부와 관계없이 먼저 안내합니다. 건강 경로는 병원 문의를 돕는 정보이며 질병 진단이나 처방이 아닙니다.</p></section></div>{selected&&<RecordDetail record={selected} pet={pet} onClose={()=>setSelected(null)} onVisit={setVisit} visitTrigger={visitRef}/>} {visit&&<VisitRecordDialog visit={visit} pet={pet} onClose={()=>setVisit(null)} triggerRef={visitRef}/>}</main>}
