import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { getPetAvatar, getPetAvatarLabel } from '../assets/petAvatar'
import { getPetProfiles, setActivePetId } from '../demo/dashboardState'
import { getDemoHealthRecords } from '../demo/plusDemoState'
import '../styles/health-records.css'

function Dialog({ children, onClose, name }) { const closeRef = useRef(null); useEffect(() => { const f = e => e.key === 'Escape' && onClose(); document.addEventListener('keydown', f); document.body.style.overflow = 'hidden'; requestAnimationFrame(() => closeRef.current?.focus()); return () => { document.removeEventListener('keydown', f); document.body.style.overflow = '' } }, [onClose]); return <div className="record-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="record-dialog" role="dialog" aria-modal="true"><button ref={closeRef} className="record-close" type="button" onClick={onClose} aria-label={name + ' 닫기'}>×</button>{children}</section></div> }
function Detail({ record, pet, onClose }) { return <Dialog onClose={onClose} name="기록 상세"><p className="record-eyebrow">건강 경로 기록 · 본선 데모 예시</p><div className="record-title"><img src={getPetAvatar(pet.species)} alt={getPetAvatarLabel(pet.species)} /><div><span>{record.date}</span><h2>{pet.name} · {record.summary}</h2></div></div>{record.status === 'urgent' && <div className="record-urgent">응급 신호를 우선 안내했던 기록이에요. 실제 상태가 이어지거나 악화되면 가까운 동물병원에 연락하세요.</div>}<section className="record-detail-block"><h3>보호자가 입력한 내용</h3><p className="record-quote">“{record.input}”</p></section><section className="record-detail-block"><h3>확인한 표준 증상</h3><div className="record-tags">{record.symptoms.map(s => <span key={s}>{s}</span>)}</div></section><section className="record-detail-block"><h3>병원 문의 전 확인 사항</h3><p>{record.guidance}</p><b>{record.hospital}</b></section><div className="record-actions"><Link to="/health-check">새 건강 경로 시작하기</Link><button type="button" onClick={onClose}>닫기</button></div><small>건강 경로는 보호자 관찰 내용을 정리하고 병원 문의를 돕기 위한 정보입니다. 질병 진단이나 처방을 제공하지 않습니다.</small></Dialog> }
function PlusDialog({ onClose }) { return <Dialog onClose={onClose} name="Plus 소개"><p className="record-eyebrow">ANIMAL-ROUTE PLUS · 본선 데모</p><h2>기록을 더 오래, 더 편하게 관리해요</h2><p className="record-description">핵심 증상 확인과 응급 안내는 언제나 무료입니다. Plus는 반복되는 기록과 일정을 관리하는 데모 옵션이에요.</p><ul><li>반려동물별 전체 건강 경로 모아보기</li><li>월별 증상 변화와 병원 문의용 요약</li><li>예방·검진·복약 일정과 알림</li></ul><button className="record-primary" type="button" onClick={onClose}>Plus 기능 미리보기</button><small>실제 결제·구독·서버 저장은 아직 연결되지 않은 본선 데모입니다.</small></Dialog> }
export default function HealthRecords() { const { pets, activePetId: stored } = getPetProfiles(); const [params,setParams] = useSearchParams(); const [petId,setPetId] = useState(params.get('pet') || stored || pets[0]?.id); const [selected,setSelected] = useState(null); const [plus,setPlus] = useState(false); const pet = pets.find(p => p.id === petId) || pets[0]; const records = pet ? getDemoHealthRecords(pet.id) : []; const changePet = id => { setPetId(id); setActivePetId(id); setParams({pet:id}) }; if (!pet) return <main className="records-page"><section className="records-empty"><h1>등록된 반려동물이 없어요</h1><Link to="/my">내 대시보드로 돌아가기</Link></section></main>; return <main className="records-page"><div className="records-shell"><Link className="records-back" to="/my">← 내 대시보드</Link><header className="records-hero"><div><p className="record-eyebrow">MY ANIMAL-ROUTE · DEMO</p><h1>우리 아이의 건강 기록</h1><span>증상 확인 결과와 병원 문의 준비 내용을 날짜별로 모아볼 수 있어요.</span></div><aside><b>최근 기록 3건</b><button type="button" onClick={()=>setPlus(true)}>전체 기록 관리 <em>Plus</em></button></aside></header><p className="records-notice">이 화면은 본선 데모 예시입니다. 실제 서버에 건강 기록을 저장하지 않으며, 진단 기록이 아닙니다.</p><div className="records-pets" role="tablist">{pets.map(p => <button key={p.id} role="tab" aria-selected={p.id===pet.id} className={p.id===pet.id?'is-active':''} onClick={()=>changePet(p.id)}><img src={getPetAvatar(p.species)} alt=""/><span>{p.name}</span></button>)}</div><section className="records-list"><header><div><h2>{pet.name}의 최근 건강 경로</h2><span>최근 3개월 · 보호자가 확인한 내용</span></div><button type="button" onClick={()=>setPlus(true)}>기간별 보기 <em>Plus</em></button></header><div className="record-timeline">{records.slice(0,3).map(r => <button type="button" className={'record-row '+(r.status==='urgent'?'is-urgent':'')} key={r.id} onClick={()=>setSelected(r)}><time>{r.date}</time><div><span className="record-status">{r.status==='urgent'?'! 응급 우선 안내':'✓ 표준 증상 확인 완료'}</span><strong>{r.summary}</strong><small>기록 보기 →</small></div></button>)}</div><button className="records-lock" type="button" onClick={()=>setPlus(true)}><span>Plus</span><div><strong>이전 기록과 월별 변화 보기</strong><small>반려동물별 전체 기간 기록과 증상 변화를 Plus에서 모아볼 수 있어요.</small></div><b>미리보기 →</b></button></section><section className="records-safety"><b>⌁</b><p>응급 신호는 구독 여부와 관계없이 먼저 안내합니다. 건강 경로는 병원 문의를 돕는 정보이며 질병 진단이나 처방이 아닙니다.</p></section></div>{selected&&<Detail record={selected} pet={pet} onClose={()=>setSelected(null)}/>} {plus&&<PlusDialog onClose={()=>setPlus(false)}/>}</main> }
