import { useKGOverview } from '../hooks'
import { kgSnapshot } from '../data/kgSnapshot'

const nodes = [
  ['보호자 표현', 'DS14', '#0f766e'], ['DS13 표준 증상', '516개', '#2563eb'], ['DS27 질병', '37개 정본 노드', '#7c3aed'], ['진료 문의 분야', '관계 22개', '#9333ea'], ['동물병원', '5,373개 노드', '#b45309'], ['생활·환경 시설', 'DS11·12·30', '#0891b2'], ['분실·구조동물', 'DS08·09·32', '#e11d48'], ['건강 관측', '112,332건', '#475569'],
]
export default function KnowledgeGraph() {
  const { data, isError } = useKGOverview(); const overview = data || kgSnapshot
  return <div className="space-y-5 max-w-[1400px]"><header><p className="text-xs font-bold tracking-wider" style={{ color: '#0f766e' }}>RDF / TURTLE GRAPH</p><h1 className="text-2xl font-bold mt-1" style={{ color: 'var(--text)' }}>지식그래프 구조와 연결 상태</h1><p className="text-sm mt-2" style={{ color: 'var(--muted)' }}>기준일 {overview.as_of} · 노드 수만 강조하지 않고, 어떤 관계가 확정·후보·미확인인지 함께 표시합니다. {isError && '로컬 스냅샷 표시 중'}</p></header>
    <section className="rounded-2xl p-5" style={{ background: 'var(--bg2)', border: '1px solid var(--border)' }}><h2 className="font-bold" style={{ color: 'var(--text)' }}>핵심 탐색 그래프</h2><div className="mt-5 grid gap-3 md:grid-cols-4">{nodes.map(([name, detail, color], i) => <div className="relative rounded-xl p-4" key={name} style={{ border: `1px solid ${color}55`, background: `${color}0d` }}><p className="text-xs font-bold" style={{ color }}>{i < 5 ? `진료 경로 ${i + 1}` : '확장 레이어'}</p><p className="font-bold mt-2" style={{ color: 'var(--text)' }}>{name}</p><p className="text-xs mt-1" style={{ color: 'var(--muted)' }}>{detail}</p></div>)}</div><div className="mt-5 rounded-xl p-4 text-sm" style={{ background: '#f8fafc', color: '#475569' }}>대표 질의: <strong>보호자 원문 → 표준 증상 → 질병 가능성 → 진료 문의 분야 → 지역 병원 후보</strong>. 이는 진단 결과가 아닌 보호자의 탐색·문의 의사결정 지원 경로입니다.</div></section>
    <section className="rounded-2xl p-5" style={{ background: 'var(--bg2)', border: '1px solid var(--border)' }}><h2 className="font-bold" style={{ color: 'var(--text)' }}>RDF 관계별 현황</h2><div className="space-y-3 mt-4">{overview.relations.map(row => <div className="grid gap-2 items-center md:grid-cols-[1fr_1fr_1fr_90px_130px] rounded-xl p-4" key={`${row.from}-${row.predicate}`} style={{ background: 'var(--bg3)' }}><span className="font-semibold">{row.from}</span><span className="font-mono text-xs" style={{ color: '#2563eb' }}>— {row.predicate} →</span><span className="font-semibold">{row.to}</span><strong className="md:text-right">{row.count}</strong><span className="text-xs md:text-right" style={{ color: row.status.includes('확정') ? '#0f766e' : '#b45309' }}>{row.status}</span></div>)}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl p-5" style={{ background: 'var(--bg2)', border: '1px solid var(--border)' }}><h2 className="font-bold" style={{ color: 'var(--text)' }}>정본화 원칙</h2><ol className="mt-4 space-y-3 text-sm" style={{ color: 'var(--muted)' }}><li>1. 관계 하나는 하나의 트리플로 저장합니다.</li><li>2. 출처·신뢰도·검수 상태는 관계 단위로 보존합니다.</li><li>3. 후보 연결은 확정 연결과 다른 상태값으로 저장합니다.</li><li>4. 통합 TTL은 개별 TTL 재생성 후에만 갱신합니다.</li></ol></div><div className="rounded-2xl p-5" style={{ background: '#fff7ed', border: '1px solid #fed7aa' }}><h2 className="font-bold" style={{ color: '#9a3412' }}>현재 추론 한계</h2><ul className="mt-4 space-y-3 text-sm" style={{ color: '#9a3412' }}>{overview.boundaries.map(x => <li key={x}>• {x}</li>)}</ul></div></section>
  </div>
}
