import { kgSnapshot } from '../data/kgSnapshot'

const pipelines = [
  { id: 'DS14', source: '보호자 자연어 원문', normalize: 'DS13 표준 증상 후보·최종 선택', relation: 'selectedSymptom / derivedFromMapping', output: '증상 탐색 입력', count: '승인 관계 40건', state: '검수 확정' },
  { id: 'DS27', source: 'DS13 표준 증상', normalize: '질병 정본 URI', relation: 'indicatesDisease / hasSymptom', output: '질병 가능성 탐색', count: '관계 145건', state: '그래프 관계' },
  { id: 'DS29', source: '병원·약국 공공데이터', normalize: '시설 URI·좌표·운영정보', relation: 'operatingHours / homepage', output: '시설 탐색 보강', count: '고유 시설 3,460곳', state: '신뢰도 저장' },
  { id: 'DS32', source: '분실·구조동물 속성', normalize: '종·성별·지역·시점 비교', relation: 'matchingCandidate', output: '재회 후보 탐색', count: '후보 882건', state: '후보 연결' },
  { id: 'DS33', source: '등록 업종 데이터', normalize: '시설·서비스 유형', relation: 'offersServiceType', output: '생활 서비스 필터', count: '관계 5,921건', state: '등록 업종 기반' },
]
const color = { '검수 확정': '#0f766e', '그래프 관계': '#2563eb', '신뢰도 저장': '#7c3aed', '후보 연결': '#b45309', '등록 업종 기반': '#475569' }

export default function Mapping() {
  return <div className="space-y-5 max-w-[1400px]"><header><p className="text-xs font-bold tracking-wider" style={{ color: '#0f766e' }}>MAPPING TABLE</p><h1 className="text-2xl font-bold mt-1" style={{ color: 'var(--text)' }}>정규화·매핑 관계 관리</h1><p className="text-sm mt-2" style={{ color: 'var(--muted)' }}>관계 하나를 하나의 RDF 관계로 저장합니다. 복수 증상을 하나의 코드 문자열로 묶지 않으며, 후보 관계와 확정 관계를 구분합니다.</p></header>
    <section className="rounded-2xl p-5" style={{ background: 'var(--bg2)', border: '1px solid var(--border)' }}><h2 className="font-bold" style={{ color: 'var(--text)' }}>원천 → 정규화 → 관계 → 서비스 흐름</h2><div className="overflow-x-auto mt-4"><table className="w-full text-sm min-w-[900px]"><thead><tr className="text-left border-b" style={{ borderColor: 'var(--border)', color: 'var(--muted)' }}><th className="pb-3">레이어</th><th className="pb-3">원천</th><th className="pb-3">정규화 결과</th><th className="pb-3">RDF 관계</th><th className="pb-3">서비스 사용</th><th className="pb-3 text-right">수치·상태</th></tr></thead><tbody>{pipelines.map(row => <tr key={row.id} className="border-b last:border-0" style={{ borderColor: 'var(--border)' }}><td className="py-4 font-mono text-xs" style={{ color: '#2563eb' }}>{row.id}</td><td className="py-4">{row.source}</td><td className="py-4">{row.normalize}</td><td className="py-4 font-mono text-xs">{row.relation}</td><td className="py-4">{row.output}</td><td className="py-4 text-right"><p className="font-bold">{row.count}</p><span className="text-xs" style={{ color: color[row.state] }}>{row.state}</span></td></tr>)}</tbody></table></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl p-5" style={{ background: 'var(--bg2)', border: '1px solid var(--border)' }}><h2 className="font-bold" style={{ color: 'var(--text)' }}>DS14 최종 검수 규칙</h2><ul className="space-y-3 mt-4 text-sm" style={{ color: 'var(--muted)' }}><li>• 검수 원문 25건은 approved 9건, rejected 16건으로 종결되었으며 needs_revision은 0건입니다.</li><li>• 승인 결과는 증상별 40개의 원자 관계로 분할되어 TTL에 반영됩니다.</li><li>• rejected 항목은 최종 증상 코드를 비우고 TTL을 생성하지 않습니다.</li><li>• 검수자는 임상 진단을 확정하지 않으며, 원문 표현과 표준 증상 간의 대응만 확인합니다.</li></ul></div><div className="rounded-2xl p-5" style={{ background: '#fff7ed', border: '1px solid #fed7aa' }}><h2 className="font-bold" style={{ color: '#9a3412' }}>후보·확정·검증의 구분</h2><ul className="space-y-3 mt-4 text-sm" style={{ color: '#9a3412' }}><li>• DS32의 882건은 이미지 동일성 판정이 아닌 속성 기반 후보입니다.</li><li>• DS33의 5,921건은 등록 업종에 따른 서비스 유형이며, 실시간 제공 여부가 아닙니다.</li><li>• 병원 역량은 공공 시설 정보와 별개입니다. 24시간·응급·전문진료·현재 가능 여부는 검증 전 확정값으로 사용하지 않습니다.</li></ul></div></section>
    <section className="rounded-2xl p-5" style={{ background: 'var(--bg2)', border: '1px solid var(--border)' }}><h2 className="font-bold" style={{ color: 'var(--text)' }}>현재 통합 관계 목록</h2><div className="grid mt-4 gap-3 md:grid-cols-2">{kgSnapshot.relations.map(row => <div className="rounded-xl p-4" key={row.predicate} style={{ background: 'var(--bg3)' }}><p className="font-mono text-xs" style={{ color: '#2563eb' }}>{row.predicate}</p><p className="font-semibold mt-2">{row.from} → {row.to}</p><div className="flex justify-between mt-2 text-sm"><strong>{row.count}</strong><span style={{ color: color[row.status] || '#b45309' }}>{row.status}</span></div></div>)}</div></section>
  </div>
}
